### PR TITLE
Fix passthrough support with axios 1.2

### PR DESCRIPTION
**Pull request by marcbachmann**
Fixes https://github.com/ctimmerm/axios-mock-adapter/issues/357

### CODE REVIEW

**Comment by marcbachmann** [comment]
argh. the baseURL somehow changes from one version to another.
v0.17.0 works with the `baseURL: null` override. v1.2 doesn't

**Comment by teetotum** [comment]
If I understand it correctly your fix is to call the (unmocked) axios API (with the current request configuration, and without any transformations) when a passthrough is to be performed.
(I'm a bit embarressed that I haven't thought about that as a possible fix when I attempted a fix for my own mock library)

Are there any ramifications?
By stripping all transformations from the "inner call" you counteract one of those ramifications, right? I.e. that the transformations would run once too often.
Does axios do any other things besides transformations before the adapter is called?
What with interceptors? Would for example a `LoggingInterceptor` now log two entries for the request when it should only log once?

I still hope for a positive reaction from the axios maintainers regarding a proposal for making the default adapter available.

**Comment by marcbachmann** [comment]
> Are there any ramifications?
By stripping all transformations from the "inner call" you counteract one of those ramifications, right? I.e. that the transformations would run once too often.

You're right, the interceptors are probably called twice. We could clone the instance during instantiation. Then interceptors won't get copied.

I think everything else config-based is only handled by the adapter.

**Comment by marcbachmann** [comment]
I've extended the tests with a counter for the request and response interceptors.
This should be good to merge.

**Comment by marcbachmann** [comment]
@ctimmerm This pr fixes compatibility with axios 1. would you like to review that?

**Comment by marco-gagliardi** [comment]
hello @ctimmerm , can this fix be merged? :)

**Comment by farhan-helmy** [comment]
+1 @marco-gagliardi

**Comment by marcbachmann** [comment]
@ctimmerm feel free to add me as maintainer here and on npm if you don't have the time to maintain this module.

**Comment by marcbachmann** [comment]
I got access to github & npm and released that change as v1.21.3.
https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v1.21.3
https://www.npmjs.com/package/axios-mock-adapter

**Comment by marcbachmann** [comment]
Somehow the `prepublish` script didn't run completely.
The `axios-mock-adapter.js` file isn't there. 🤔 
Just the minified version: image

**Comment by steveatkoan** [comment]
thanks so much! this fix allows me to upgrade axios now. Very appreciated

**Pull request merged**
