### PR TITLE
Add support for parameters serialization

### PR DESCRIPTION
**Pull request by Kocal**
PR related to issue #120.

### CODE REVIEW

**Comment by Kocal** [comment]
Well, it seems that some Travis builds have been timed out :confused:

**Comment by rerodrigues** [comment]
+1 for this

**Comment by Kocal** [comment]
PR rebased.

**Comment by tconroy** [comment]
+1, would be very useful addition.

**Comment by ShakurOo** [comment]
Already opened ? ...

**Comment by Kocal** [comment]
Looks like, but I didn't use axios/axios-mock-adapter for a very long time... feel free to re-open a rebased PR if needed! :)

**Pull request closed without merging**
