### PR TITLE
doc: Use AxiosMockAdapter throughout README

### PR DESCRIPTION
**Pull request by exoego**
```javascript
import MockAdapter from 'axios-mock-adapter'
```
works too, but `AxiosMockAdapter` is a preferred term.

### CODE REVIEW

**Comment by exoego** [comment]
@marcbachmann Could you take a look?

**Comment by marcbachmann** [comment]
I'm not sure how this would fix anything. you need to import `AxiosMockAdapter` instead of `MockAdapter`

**Comment by exoego** [comment]
Hmm, but
```javascript
// works
import MockAdapter from 'axios-mock-adapter'

// don't
import AxiosMockAdapter from 'axios-mock-adapter'
```

**Comment by exoego** [comment]
Ah sorry, `AxiosMockAdapter` works too.

In example of README, `MockAdapter` is used.
So I thought it was a wrong name, but both is fine.
https://github.com/ctimmerm/axios-mock-adapter?tab=readme-ov-file#example

**Comment by marcbachmann** [comment]
If you change all `MockAdapter` occurences to `AxiosMockAdapter` in the Readme and remove the webpack config change, I could approve the change 😉

**Comment by exoego** [comment]
@marcbachmann I see. Fixed the PR.

**Review by marcbachmann — APPROVED** [review]

**Pull request merged**
