### PR TITLE
Support matching query params for `post`, `put` methods.

### LINKED ISSUE #88: Mock a post request with data and query params
Firstly: Thanks for the great tool!

Now for my issue:

How can I mock a post request which checks both data and query params?

The production code looks like this:

```
const getReport = (userId, managerId, start, count, refresh) => {
  return axios.post(url(userId),
    {
      ManagerId: managerId
    }, {
      withCredentials: true,
      start,
      count,
      refresh
    }).then(extractData)
}
```

The tests I have

```
      mock.onPost(`http://localhost:3000/example/api/users/${userId}/reports/data`,
        {
          ManagerId: managerId
        }, {
          params: {
            withCredentials: true,
            start,
            count,
            refresh
          }
        }
      ).replyOnce(200, reportGenerator(start, count))
```

However the params don't seem to matter, I can leave them out, change them, the mock always returns the same data. If I change the body (managerId) then the mock does not return the data, which is what I expect.

How can I mock axios, so that the mocked data is only returned if URL matches, the query params match, and the data match?

Thanks

### PR DESCRIPTION
**Pull request by thk2b**
This PR closes #88 and #129.

Currently, it is possible to expect query params for `GET`, or a specific body for `POST`, but it is impossible to expect specific query params and a specific body.

To solve this, I added a fourth argument to `MockAdapter.prototype[methodName]` (ie. `onPost`, `onGet`), which corresponds to the expected query parameters for the request. This allows matching both a body and parameters for methods that have a body (`PUT`, `POST`, ...).

This is entirely backwards compatible, meaning that we can still match the params for `GET`, `DELETE`, etc... by specifying the expected params as the second argument (in place of the expected body as for `PUT` and `POST` methods). Overall, this PR does not affect the behaviour of the current public api, since it only adds an argument.

This test case demonstrates the new behaviour:
```js
it('can pass a body, query params, and headers to match a handler', function() {
  var headers = {
    Accept: 'application/json, text/plain, */*',
    'Content-Type': 'application/x-www-form-urlencoded',
    'Header-test': 'test-header'
  };
  mock.onPost('/withBodyAndParams', { data: { is: 'passed' }, in: true }, headers, { foo: 'bar', bar: 'baz' }).reply(200);
  
  return instance
    .post('/withBodyAndParams', { data: { is: 'passed' }, in: true }, { headers: headers, params: { foo: 'bar', bar: 'baz' }})
    .then(function(response) {
      expect(response.status).to.equal(200);
    });
});
```

Implementing this required adding the expected request parameters to the `handler` array. All indexes throughout the source were incremented as needed. Then, we check that the params do match in `utils.findHandler`.

I added several new test cases.

I also modified some tests involving matching params, where the expected params were passed inside the `params` key of an object. This was not required, and I'm not sure why the tests passed in the first place. See [this commit](https://github.com/ctimmerm/axios-mock-adapter/commit/b30fe69f1a07bd564f3f75eecbc8cb4b837aeb03).

### CODE REVIEW

**Comment by thk2b** [comment]
@ctimmerm , can you let me know if anything can be improved ? Thanks !

**Comment by thk2b** [comment]
@ctimmerm Hello Colin,

Again, may I get some feedback on this PR ? I'd really like to get this merged. If something is wrong please let me know and I will work on it.

Thank you for your time !

**Comment by clockworked247** [comment]
@ctimmerm @thk2b It'd be great to get this feature in!  Usage of params with POST/PUT requests shows up in the Axios docs and I'm sure many developers need this feature to properly filter which requests to mock.  

Right now my not-so-great-work-around without this feature is to check the params in the reply 

```
    mock.onPost(/\/path.+/).reply(function(config) {
      return new Promise(function(resolve, reject) {
        if (config.params 
            && config.params.querytype === 'xquery'
            && config.params.action === 'profile') {
          headers.qid = config.params.qid;
          resolve([200, evalerBody, headers]);
        }
        else
          reject();  // this is not what I want to do, would prefer to trigger a passThrough
      })
    });
```

Since I have to way to trigger a pass through within the reply, I need the ability to filter up front as a part of the onPost call with params.

**Comment by jDeppen** [comment]
Thanks, @clockworked247 (and @thk2b).
For posterity, here's how I handled mine (stripped down version) with Jest snapshots. I only need to ensure the correct data is being sent.
```
it('example test', () => {
  let actualData
  mock.onPost(url).reply(config => {
    actualData = config.data
    return new Promise(resolve => resolve([200, responseBody, headers]))
  })

  return store.dispatch(fnToTest()).then(() => {
    expect(JSON.parse(actualData)).toMatchSnapshot()
  })
})
```

**Comment by keeganwitt** [comment]
Should #88 or #129 be reopened since this never got merged?

**Comment by renanzulian** [comment]
Do you know when this feature will be merged?

**Comment by mvitz** [comment]
Any news if or when this does get merged?

**Comment by nasyarobby** [comment]
any news? it's like 2023 already.

**Comment by marcbachmann** [comment]
[v2.0.0](https://github.com/ctimmerm/axios-mock-adapter/releases/tag/v2.0.0) is released with support for `onPost(url, body, {params, headers})`

**Pull request closed without merging**
