### PR TITLE
Added possility of setting response delay time

### PR DESCRIPTION
**Pull request by hugofelp**
I have included an optional parameter in the constructor that sets a delay time (in milliseconds) for all responses.
Docs have also been updated.
Thanks

### CODE REVIEW

**Comment by ctimmerm** [comment]
Thanks for you pull request! Could you give an example of how this can be useful or what your specific use case is?

**Comment by hugofelp** [comment]
I added this feature to get a more realistic experience when simulating requests.
On my case, I wanted to make sure the loading state of my components are consistently implemented.

**Comment by ctimmerm** [comment]
Ok, that makes sense. Could you rebase your branch on the latest master so that it can be merged?
I also have two small suggestions:
 * The second argument to the `MockAdapter` function can be an options object so that we can later on easily add more options:

 ```js
var mock  = new MockAdapter(axios, { delayResponse: 2000 });
 ```
 * With your commit, all responses have become asynchronous. To keep debugging easy it would be better to keep responses synchronous if no delay is given.

**Comment by hugofelp** [comment]
Done. Thanks for the suggestions.

**Pull request merged**
