### PR TITLE
support stream, buffer as response, fix coverage

### PR DESCRIPTION
**Pull request by StarpTech**
This PR will fix https://github.com/ctimmerm/axios-mock-adapter/issues/153

* Support stream and buffer as response
* Fixed coverage script

### CODE REVIEW

**Comment by dir01** [comment]
Would like to see this merged. @ctimmerm do you generally approve this pull request? All good conceptually? I could polish it a bit, make tests pass, solve conflicts, fix typos, will it be mergeable then?

**Comment by addijhaq** [comment]
what needs to be done to have this pr merged?

**Comment by StarpTech** [comment]
@addijhaq maintainers 😄

**Comment by sr258** [comment]
Would be really great if this PR was accepted!

**Comment by cmwd** [comment]
I'd very much appreciate this feature ✌️:)

**Pull request merged**
