### PR TITLE
match request parameters

### PR DESCRIPTION
**Pull request by sakumikko**
Hi

We needed the ablity to match request paramaters so here is the changeset.
#18 
Saku

### CODE REVIEW

**Comment by ctimmerm** [comment]
Thanks!

**Comment by CodinCat** [comment]
Hi,

Is there any plan to release next version to npm?

Since there are several PRs were merged, it would be great to have this update.

thanks.

**Comment by ctimmerm** [comment]
True, I'll publish a new version today.

**Comment by mfonsen** [comment]
This change seems to break existing functionality suggested in #18.

Tried adding the following test case with the following test case to `basic.spec.js`:
```
  it('passes the config to the callback even with params', function() {
    mock.onGet(/\/products\/\d+/).reply(function(config) {
      return [200, {}, { RequestedURL: config.url }];
    });

    return instance.get('/products/25', { params: { name: 'Bob' }})
      .then(function(response) {
        expect(response.headers.RequestedURL).to.equal('/products/25');
      });
  });
```
That returns `400`.

**Pull request merged**
