### PR TITLE
Validate handlers using request headers

### PR DESCRIPTION
**Pull request by rmartins90**
Request made at issue #69 .

### CODE REVIEW

**Comment by ctimmerm** [comment]
Thanks! I'll release a new version this weekend that includes this.

**Comment by zplata** [comment]
@ctimmerm Any updates for getting this in a next release?

**Comment by soswow** [comment]
It seems like it was released, but @types were not updated

**Comment by jan-molak** [comment]
@soswow - Well spotted, I've just submitted a patch for that.

**Pull request merged**
